# General playback settings
save-position-on-quit
resume-playback=yes
screenshot-format=png
screenshot-directory=~/Pictures/mpv_screenshots

# Volume settings
volume-max=200
audio-normalize-downmix=yes

vo=gpu-next
