#!/usr/bin/env bash

if command -v eza >/dev/null; then
  alias ls='eza -l --icons --group-directories-first'
  alias la='eza -l --icons --group-directories-first --long --all'
fi

# neovim alias
alias nv='nvim'

# cd alias
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# package management
alias s='pacman -Ss'
alias si='sudo pacman -S'
alias y='yay -Ss'
alias yi='yay -S'

if command -v rustormy >/dev/null; then
  alias weather='rustormy -c Ranchi --colors'
fi
