# Applications
exec-once = setsid waybar
exec-once = setsid hypridle
exec-once = setsid hyprsunset
exec-once = setsid swww-daemon
exec-once = setsid swayosd-server

# Clipboard
exec-once = setsid wl-paste --type text --watch cliphist store
exec-once = setsid wl-paste --type image --watch cliphist store

# Setting variables for wayland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
