-- Cursor size
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Original-Classic")
hl.env("HYPRCURSOR_THEME", "Bibata-Original-Classic")

-- Force all apps to use Wayland
-- TODO: manual review — malformed env on line 8: GDK_BACKEND,wayland,x11,*
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
-- env = QT_STYLE_OVERRIDE,kvantum
hl.env("QT_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("XDG_SESSION_TYPE", "wayland")
-- qt based apps themes
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- Allow better support for screen sharing (Google Meet, Discord, etc)
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.env("XDG_MENU_PREFIX", "plasma-")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- Environment
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_MENU_PREFIX", "plasma-")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")

hl.env("TERMINAL", "kitty")
hl.env("EDITOR", "nvim")
hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
    -- Don't show update on first launch
    ecosystem = {
        no_update_news = true,
    },
    -- System wide terminal
})

