# Cursor size
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
# env = QT_STYLE_OVERRIDE,kvantum
env = QT_SCALE_FACTOR,1
env = QT_ENABLE_HIGHDPI_SCALING,1
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland
# qt based apps themes
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct

# Allow better support for screen sharing (Google Meet, Discord, etc)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

env = XDG_MENU_PREFIX,plasma-
env = XDG_CURRENT_DESKTOP,Hyprland

# Environment
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_MENU_PREFIX,plasma-
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

xwayland {
  force_zero_scaling = true
}

# Don't show update on first launch
ecosystem {
  no_update_news = true
}

# System wide terminal
env = TERMINAL,kitty
env = EDITOR,nvim
