source = ~/.config/hypr/themes/colors.conf

general {
    gaps_in = 4
    gaps_out = 6
    border_size = 2

    col.active_border = $foreground
    col.inactive_border = $background
    col.active_border = $color1 $color2 $color3 90deg

    allow_tearing = false
}

decoration {
    rounding = 10
    rounding_power = 2
    blur {
        enabled = true
        size = 3
        passes = 3
        ignore_opacity = true
        noise = 0.0117
        contrast = 0.8916
        xray = false
        new_optimizations = true
    }
}

dwindle {
    # I think it makes the current window smaller and another one bigger
    # Using C-p does this
    pseudotile = true
    preserve_split = true # You probably want this
}

master {
    new_status = dwindle
}
