source = ~/.config/hypr/themes/colors.conf

general {
    gaps_in = 4
    gaps_out = 6
    border_size = 2

    col.active_border = $foreground
    col.inactive_border = $background
    col.active_border = $color1 $color2 $color3 90deg

    allow_tearing = false
}

decoration {
    rounding = 10
    rounding_power = 2
}

dwindle {
    # I think it makes the current window smaller and another one bigger
    # Using C-p does this
    pseudotile = true
    preserve_split = true # You probably want this
}

master {
    new_status = dwindle
}
