source = ~/.config/hypr/themes/colors.conf

general {
    gaps_in = 0
    gaps_out = 0

    border_size = 2

# https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $foreground
    col.inactive_border = $background
    col.active_border = $color1 $color2 $color3 90deg

# Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

master {
    new_status = master
}
