-- Default laptop screen
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "highres",
    position = "auto",
    scale = "1.25",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@100",
    position = "auto",
    scale = "1",
})

hl.env("GDK_SCALE", "1")
hl.env("GDK_DPI_SCALE", "1")
hl.env("GDK_BACKEND", "wayland")
