-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", allow = "allow" })

hl.config({
    ecosystem = {
        enforce_permissions = true,
    },
    -- Always allow grim to capture screen w/o asking
    -- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
    -- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
})

