# Floating windows
source = ~/.config/hypr/utilities/apps.conf
source = ~/.config/hypr/utilities/webcam-overlay.conf

# Stay focused on TUI windows & wait for them to close
windowrule = stayfocused, title:(Bluetui)
windowrule = stayfocused, title:(Wiremix)

# Scroll nicely in the terminal
windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Blur these programs
layerrule = blur, waybar
layerrule = blur, swww-daemon
