-- Floating windows
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/utilities/apps.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.hypr.utilities.apps")
-- Source: ~/.config/hypr/utilities/webcam-overlay.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.hypr.utilities.webcam-overlay")

-- Stay focused on TUI windows & wait for them to close
hl.window_rule({
    match = {
        title = "Bluetui",
    },
    -- TODO: manual review — unmapped window rule action: "stay_focused true"
})

hl.window_rule({
    match = {
        title = "Wiremix",
    },
    -- TODO: manual review — unmapped window rule action: "stay_focused true"
})

-- Scroll nicely in the terminal
hl.window_rule({
    match = {
        class = "(Alacritty|kitty)",
    },
    -- TODO: manual review — unmapped window rule action: "scroll_touchpad 1.5"
})

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    -- TODO: manual review — unmapped window rule action: "no_focus on"
})
