source = ~/.config/hypr/themes/colors.conf

# BACKGROUND
background {
    monitor =
    # path = $wallpaper
    path = screenshot
    blur_passes = 3
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# ANIMATIONS
animations {
    enabled = false
  }

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = $foreground
    font_size = 80
    font_family = JetBrainsMono Nerd Font
    position = 0, 100
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 650, 100
    outline_thickness = 4
    dots_center = true

    outer_color = $foreground
    inner_color = $background
    check_color = $color1
    font_color = $color2
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i>Password...</i>
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    fade_on_empty = false
    hide_input = false

    position = 0, -100
    halign = center
    valign = center
}
