# Window manager tiling config
source = ~/.config/hypr/tiling/animations.conf
source = ~/.config/hypr/tiling/autostart.conf
source = ~/.config/hypr/tiling/binds.conf
source = ~/.config/hypr/tiling/envs.conf
source = ~/.config/hypr/tiling/input.conf
source = ~/.config/hypr/tiling/looknfeel.conf
source = ~/.config/hypr/tiling/monitors.conf
source = ~/.config/hypr/tiling/windows.conf
