# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[](#0000FF)'
error_symbol = '[](#FF0000)'
vicmd_symbol = '[△](#6A9589)'

[directory]
truncation_length = 8
truncation_symbol = '…/'
