windowrule = float, tag:floating-window
windowrule = center, tag:floating-window
windowrule = size 800 600, tag:floating-window
windowrule = rounding 10, floating:1

# Float proton vpn
windowrule = tag +floating-window, class:(protonvpn-app)

# Float gapless music player
windowrule = tag +floating-window, class:(com.github.neithern.g4music)

# Float mpv
windowrule = tag +floating-window, class:(mpv)

# Float Nautilus sushi previewer
windowrule = tag +floating-window, class:(org.gnome.NautilusPreviewer)

# Float qbittorrent
windowrule = tag floating-window, class:(org.qbittorrent.qBittorrent)

# Float imv image viewer
windowrule = tag +floating-window, class:(imv)

# Float gnome boxes
windowrule = tag +floating-window, class:(org.gnome.Boxes)

# Wifi menu in TUI
windowrule = float, class:(Wifitui)
windowrule = center, class:(Wifitui)
windowrule = size 700 550, class:(Wifitui)
windowrule = stayfocused, class:(Wifitui)

# Float ticktick
windowrule = float, class:(ticktick)
windowrule = center, class:(ticktick)
windowrule = size 680 650, class:(ticktick)

# Float gnome clocks
windowrule = tag +floating-window, class:(org.gnome.clocks)

# Float telegram
windowrule = tag +floating-window, class:(org.telegram.desktop)

# Localsend
windowrule = float, class:(localsend)
windowrule = size 200 90, class:(localsend)

# Waybar
layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.5, waybar

# Kitty
windowrulev2 = opacity 0.9 0.9, class:^(kitty)$
# optional: keep full opacity in fullscreen
windowrulev2 = opacity 0.9 0.9 1.0, class:^(kitty)$

# Float TUI.float class apps
windowrule = tag +floating-window, class:(TUI.float)

# Browser types
windowrule = tag +chromium-based-browser, class:((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable|helium)
windowrule = tag +firefox-based-browser, class:([fF]irefox|zen|librewolf)
# PiP Window Rules
windowrule = float,title:(Picture.?in.?[pP]icture)
windowrule = pin,title:(Picture.?in.?[pP]icture)
windowrule = size 500 308,title:(Picture.?in.?[pP]icture)
windowrule = move 100%-w-40 100%-w-40, title:(Picture.?in.?[pP]icture)

# Some video sites should never have opacity applied to them
windowrule = opacity 1.0 1.0, initialTitle:((?i)(?:[a-z0-9-]+\.)*youtube\.com_/|app\.zoom\.us_/wc/home)
