-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
	match = {
		tag = "floating-window",
	},
	float = true,
	center = true,
	size = "800 600",
	stay_focused = true,
})

-- Float proton vpn
hl.window_rule({
	match = {
		class = "protonvpn-app",
	},
	tag = "+floating-window",
})

-- Float mpv
hl.window_rule({
	match = {
		class = "mpv",
	},
	tag = "+floating-window",
})

-- Wifi menu in TUI
hl.window_rule({
	match = {
		class = "Wifitui",
	},
	float = true,
	center = true,
	size = "700 550",
})

-- Float telegram
hl.window_rule({
	match = {
		class = "org.telegram.desktop",
	},
	tag = "+floating-window",
})

-- Localsend
hl.window_rule({
	match = {
		class = "localsend",
	},
	float = true,
	size = "200 90",
})

-- Waybar
hl.layer_rule({
	match = { namespace = "match:namespace waybar" },
})

-- layerrule = ignore_zero on, match:namespace waybar
hl.layer_rule({
	match = { namespace = "match:namespace waybar" },
})

-- Kitty
hl.window_rule({
	match = {
		class = "^kitty$",
	},
	opacity = "0.9 0.9",
})

-- optional: keep full opacity in fullscreen
hl.window_rule({
	match = {
		class = "^kitty$",
	},
	opacity = "0.9 0.9 1.0",
})

-- Browser types
hl.window_rule({
	match = {
		class = "((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable|helium)",
	},
	tag = "+chromium-based-browser",
})

hl.window_rule({
	match = {
		class = "([fF]irefox|zen|librewolf)",
	},
	tag = "+firefox-based-browser",
})

-- PiP Window Rules
hl.window_rule({
	match = {
		title = "Picture.?in.?[pP]icture",
	},
	float = true,
	pin = true,
	size = "500 308",
	move = "100%-w-40 100%-w-40",
})

-- Some video sites should never have opacity applied to them
hl.window_rule({
	match = {
		initial_title = "((?i)(?:[a-z0-9-]+\\.)*youtube\\.com_/|app\\.zoom\\.us_/wc/home)",
	},
	opacity = "1.0 1.0",
})
