-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        tag = "floating-window",
    },
    float = true,
    center = true,
    size = "800 600",
    rounding = 10,
})

hl.window_rule({
    match = {
        class = "my-window",
    },
    -- TODO: manual review — unmapped window rule action: "border_size 10"
})

-- Float proton vpn
hl.window_rule({
    match = {
        class = "protonvpn-app",
    },
    tag = "+floating-window",
})

-- Float gapless music player
hl.window_rule({
    match = {
        class = "com.github.neithern.g4music",
    },
    tag = "+floating-window",
})

-- Float mpv
hl.window_rule({
    match = {
        class = "mpv",
    },
    tag = "+floating-window",
})

-- Float Nautilus sushi previewer
hl.window_rule({
    match = {
        class = "org.gnome.NautilusPreviewer",
    },
    tag = "+floating-window",
})

-- Float qbittorrent
hl.window_rule({
    match = {
        class = "org.qbittorrent.qBittorrent",
    },
    tag = "floating-window",
})

-- Float imv image viewer
hl.window_rule({
    match = {
        class = "imv",
    },
    tag = "+floating-window",
})

-- Float gnome boxes
hl.window_rule({
    match = {
        class = "org.gnome.Boxes",
    },
    tag = "+floating-window",
})

-- Wifi menu in TUI
hl.window_rule({
    match = {
        class = "Wifitui",
    },
    float = true,
    center = true,
    size = "700 550",
    -- TODO: manual review — unmapped window rule action: "stay_focused on"
})

-- Float ticktick
hl.window_rule({
    match = {
        class = "ticktick",
    },
    float = true,
    center = true,
    size = "680 650",
})

-- Float gnome clocks
hl.window_rule({
    match = {
        class = "org.gnome.clocks",
    },
    tag = "+floating-window",
})

-- Float telegram
hl.window_rule({
    match = {
        class = "org.telegram.desktop",
    },
    tag = "+floating-window",
})

-- Localsend
hl.window_rule({
    match = {
        class = "localsend",
    },
    float = true,
    size = "200 90",
})

-- Waybar
hl.layer_rule({
    match = { namespace = "match:namespace waybar" },
    -- TODO: manual review — unmapped layer rule: "blur on"
})

-- layerrule = ignore_zero on, match:namespace waybar
hl.layer_rule({
    match = { namespace = "match:namespace waybar" },
    -- TODO: manual review — unmapped layer rule: "ignore_alpha 0.5"
})

-- Kitty
hl.window_rule({
    match = {
        class = "^kitty$",
    },
    opacity = "0.9 0.9",
})

-- optional: keep full opacity in fullscreen
hl.window_rule({
    match = {
        class = "^kitty$",
    },
    opacity = "0.9 0.9 1.0",
})

-- Float TUI.float class apps
hl.window_rule({
    match = {
        class = "TUI.float",
    },
    tag = "+floating-window",
})

-- Browser types
hl.window_rule({
    match = {
        class = "((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable|helium)",
    },
    tag = "+chromium-based-browser",
})

hl.window_rule({
    match = {
        class = "([fF]irefox|zen|librewolf)",
    },
    tag = "+firefox-based-browser",
})

-- PiP Window Rules
hl.window_rule({
    match = {
        title = "Picture.?in.?[pP]icture",
    },
    float = true,
    pin = true,
    size = "500 308",
    move = "100%-w-40 100%-w-40",
})

-- Some video sites should never have opacity applied to them
hl.window_rule({
    match = {
        initial_title = "((?i)(?:[a-z0-9-]+\\.)*youtube\\.com_/|app\\.zoom\\.us_/wc/home)",
    },
    opacity = "1.0 1.0",
})

