# Webcam overlay for screen recording
windowrule = match:title WebcamOverlay, float on
windowrule = match:title WebcamOverlay, pin true
windowrule = match:title WebcamOverlay, no_initial_focus on
windowrule = match:title WebcamOverlay, no_dim on
windowrule = match:title WebcamOverlay, move 100%-w-40 100%-w-40 # There's a typo in the hyprland rule so 100%-w on the height param is actually correct here
