-- Webcam overlay for screen recording
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        title = "WebcamOverlay",
    },
    float = true,
    pin = true,
    -- TODO: manual review — unmapped window rule action: "no_initial_focus on"
    -- TODO: manual review — unmapped window rule action: "no_dim on"
    move = "100%-w-40 100%-w-40",
})

