# name: Rosé Pine
# author: jishnurajendran
# upstream: https://github.com/jishnurajendran/hyprland-rosepine/blob/main/rose-pine.conf
# All natural pine, faux fur and a bit of soho vibes for the classy minimalist
$background           = 0xff191724
$foreground           = 0xffe0def4
$color1               = 0xffebbcba
$color2               = 0xffeb6f92
$color3               = 0xff31748f
$color4               = 0xff9ccfd8
