return {
  "catgoose/nvim-colorizer.lua",
  event = "BufReadPre",
  opts = {
    filetypes = {
      css = { rgb_fn = true, oklch_fn = true },
      html = { mode = 'foreground' },
      yml = { rgb_fn = true, oklch_fn = true },
      yaml = { rgb_fn = true, oklch_fn = true },
      ini = { rgb_fn = true, oklch_fn = true },
      config = { rgb_fn = true, oklch_fn = true },
      javascript = { rgb_fn = true, oklch_fn = true },
      typescript = { rgb_fn = true, oklch_fn = true },
      scss = { rgb_fn = true, oklch_fn = true },
      less = { rgb_fn = true, oklch_fn = true },
      sass = { rgb_fn = true, oklch_fn = true },
      lua = { rgb_fn = true, oklch_fn = true },
      vim = { rgb_fn = true, oklch_fn = true },
      c = { rgb_fn = true, oklch_fn = true },
      cpp = { rgb_fn = true, oklch_fn = true },
      go = { rgb_fn = true, oklch_fn = true },
      rust = { rgb_fn = true, oklch_fn = true },
      python = { rgb_fn = true, oklch_fn = true },
      java = { rgb_fn = true, oklch_fn = true },
      sh = { rgb_fn = true, oklch_fn = true },
      zsh = { rgb_fn = true, oklch_fn = true },
    },
  },
}
